# Generated by Django 4.1.5 on 2023-01-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copies',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
